#!/usr/bin/env bash
#
# Firebase Hosting Setup Wizard (Direct Terminal Deploy)
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit it.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=3

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard helps you deploy Favi directly to Firebase Hosting\n' "$DIM"
  printf '  and updates your README and installer scripts with your live domain.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup & Deployment complete%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "Firebase Hosting Direct Deploy Wizard"

# ── Stage 1: Firebase Project Selection ───────────────────────────────────
stage "Firebase Project Selection"
say "We will select or create your Firebase project."
open_url "https://console.firebase.google.com/"
step "In the Firebase Console, create a new project or select an existing one."
step "Note down your Project ID (e.g., 'use-favi' or 'favi-12345')."
ask GCP_PROJECT_ID "Enter your Firebase Project ID:"

if [[ -n "$GCP_PROJECT_ID" ]]; then
  cat <<EOF > .firebaserc
{
  "projects": {
    "default": "$GCP_PROJECT_ID"
  }
}
EOF
  say "✓ Updated .firebaserc with project '$GCP_PROJECT_ID'"
fi

# ── Stage 2: Direct Build & Firebase Deploy ───────────────────────────────
stage "Build Frontend & Deploy to Firebase Hosting"
say "We will now build the static assets and deploy them live to Firebase Hosting!"
say "If you are not logged into Firebase CLI, run 'npx firebase-tools login' when prompted."

if confirm "Proceed with building and deploying to Firebase Hosting now?"; then
  say "Building production frontend assets..."
  (cd frontend && npm run build)
  say "Deploying static assets to Firebase Hosting..."
  npx -y firebase-tools@latest deploy --only hosting --project "${GCP_PROJECT_ID:-use-favi}"
else
  warn "Skipped live deployment."
fi

# ── Stage 3: Update README & Installer URLs ───────────────────────────────
stage "Update README & Installer URLs"
DEFAULT_URL="https://${GCP_PROJECT_ID:-use-favi}.web.app"
ask LIVE_URL "Enter your live Firebase URL [default: $DEFAULT_URL]:"
[[ -z "$LIVE_URL" ]] && LIVE_URL="$DEFAULT_URL"

say "Updating README.md and installer scripts with live URL: $LIVE_URL"

sed -i "s|https://raw.githubusercontent.com/shlok377/favicon/master/install.sh|$LIVE_URL/install.sh|g" README.md 2>/dev/null || true
sed -i "s|https://raw.githubusercontent.com/shlok377/favicon/master/install.ps1|$LIVE_URL/install.ps1|g" README.md 2>/dev/null || true

say "✓ Updated README.md with $LIVE_URL"

if confirm "Commit and push updated README & installer scripts to GitHub master?"; then
  git add README.md install.sh install.ps1 frontend/public/ .firebaserc 2>/dev/null || true
  git commit -m "docs: update production Firebase Hosting URL to $LIVE_URL" 2>/dev/null || true
  git push origin master 2>/dev/null || true
  say "✓ Pushed changes to GitHub!"
else
  warn "Skipped git commit & push."
fi

finish
