#!/usr/bin/env bash
#
# Firebase Hosting & Cloud Run Setup Wizard
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit it.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=5

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "Firebase Hosting & Cloud Run Setup Wizard"

# ── Stage 1: Firebase Project Selection ───────────────────────────────────
stage "Firebase Project Selection"
say "We will select or create your Firebase project."
open_url "https://console.firebase.google.com/"
step "In the Firebase Console, create a new project or select an existing one."
step "Note down your Project ID (e.g., 'use-favi' or 'favi-12345')."
ask GCP_PROJECT_ID "Enter your Firebase Project ID:"

if [[ -n "$GCP_PROJECT_ID" ]]; then
  cat <<EOF > .firebaserc
{
  "projects": {
    "default": "$GCP_PROJECT_ID"
  }
}
EOF
  say "✓ Updated .firebaserc with project '$GCP_PROJECT_ID'"
  set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
fi

# ── Stage 2: Firebase CLI Authentication ──────────────────────────────────
stage "Firebase CLI Authentication"
say "We will authenticate with Firebase to generate a token for GitHub Actions."
step "We will run 'npx firebase-tools login:ci' to open the Google login page."
pause "Press Enter to start Firebase login..."

FIREBASE_CI_TOKEN=$(npx -y firebase-tools@latest login:ci 2>/dev/null | grep -E "1//" | tail -n1 || echo "")

if [[ -z "$FIREBASE_CI_TOKEN" ]]; then
  warn "Could not auto-capture token from login output."
  ask_secret FIREBASE_CI_TOKEN "Paste your FIREBASE_TOKEN (if generated):"
fi

if [[ -n "$FIREBASE_CI_TOKEN" ]]; then
  set_secret FIREBASE_TOKEN "$FIREBASE_CI_TOKEN"
  set_secret FIREBASE_SERVICE_ACCOUNT "$FIREBASE_CI_TOKEN"
fi

# ── Stage 3: Google Cloud Service Account for Cloud Run ───────────────────
stage "GCP Service Account Key (for Cloud Run)"
say "To deploy the backend to Cloud Run from GitHub Actions, we need a Service Account JSON Key."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=${GCP_PROJECT_ID:-use-favi}"
step "1. Click '+ CREATE SERVICE ACCOUNT'."
step "2. Name it 'github-deployer'."
step "3. Grant roles: 'Cloud Run Admin', 'Storage Admin', 'Service Account User'."
step "4. Click on the created service account -> Keys tab -> Add Key -> Create new key (JSON)."
step "5. Open the downloaded JSON file and copy its ENTIRE contents."

ask_secret GCP_SA_KEY "Paste the entire Service Account JSON contents (or press Enter to skip):"

if [[ -n "$GCP_SA_KEY" ]]; then
  set_secret GCP_SA_KEY "$GCP_SA_KEY"
fi

# ── Stage 4: Initial Web Deployment ───────────────────────────────────────
stage "Initial Web Deployment to Firebase Hosting"
say "We will now build the frontend static assets and deploy them live to Firebase Hosting!"
if confirm "Proceed with building and deploying to Firebase Hosting now?"; then
  say "Building production frontend assets..."
  (cd frontend && npm run build)
  say "Deploying static assets to Firebase Hosting..."
  npx -y firebase-tools@latest deploy --only hosting --project "${GCP_PROJECT_ID:-use-favi}"
else
  warn "Skipped live deployment."
fi

# ── Stage 5: Update README & Installer URLs ───────────────────────────────
stage "Update README & Installer URLs"
DEFAULT_URL="https://${GCP_PROJECT_ID:-use-favi}.web.app"
ask LIVE_URL "Enter your live Firebase URL [default: $DEFAULT_URL]:"
[[ -z "$LIVE_URL" ]] && LIVE_URL="$DEFAULT_URL"

say "Updating README.md and installer scripts with live URL: $LIVE_URL"

sed -i "s|https://raw.githubusercontent.com/shlok377/favicon/master/install.sh|$LIVE_URL/install.sh|g" README.md 2>/dev/null || true
sed -i "s|https://raw.githubusercontent.com/shlok377/favicon/master/install.ps1|$LIVE_URL/install.ps1|g" README.md 2>/dev/null || true

say "✓ Updated README.md with $LIVE_URL"

if confirm "Commit and push updated README & installer scripts to GitHub master?"; then
  git add README.md install.sh install.ps1 frontend/public/ .firebaserc 2>/dev/null || true
  git commit -m "docs: update production Firebase Hosting URL to $LIVE_URL" 2>/dev/null || true
  git push origin master 2>/dev/null || true
  say "✓ Pushed changes to GitHub!"
else
  warn "Skipped git commit & push."
fi

finish
